var = int(input("Input Decemal number:\n"))
print "Entered Decimal Number is : ",str(var) 
print "Hexa decimal Equavelent is: " ,hex(var)
print "Binary Equivalent is      : " ,bin(var)
print "Octal Equalent is         : " ,oct(var) 
